(() => {
const vocabGroups = [
  {
    id: "greetings",
    kind: "vocab",
    title: "问候",
    letters: ["ياخشىمۇسىز", "رەھمەت", "خوش", "ئەسسالامۇ ئەلەيكۇم"],
    goal: "先认识最常见的问候和礼貌词形，中文只做预览",
    status: "待审校",
    items: [
      {
        id: "yaxshimusiz",
        value: "ياخشىمۇسىز",
        latin: "yaxshimusiz",
        meaning: "你好、你好吗",
        theme: "问候",
        parts: ["ياخشى", "مۇ", "سىز"],
        standardNote: "候选标准问候词形，需母语者确认使用场景。",
        variantNote: "可能兼有问候和询问状态用法，语境待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "暂不考中文含义，只做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "词形较长，先分成 ياخشى、مۇ、سىز 三块看。"
      },
      {
        id: "rahmat",
        value: "رەھمەت",
        latin: "rehmet",
        meaning: "谢谢",
        theme: "问候",
        parts: ["رە", "ھمەت"],
        standardNote: "候选礼貌词，需确认标准转写和发音。",
        variantNote: "口语发音和转写可能有差异，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "暂不考中文含义，只做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "先看 ر 和 ھ，再整体记住词形。"
      },
      {
        id: "xosh",
        value: "خوش",
        latin: "xosh",
        meaning: "再见、告别",
        theme: "问候",
        parts: ["خ", "و", "ش"],
        standardNote: "候选告别词，需确认使用范围。",
        variantNote: "不同资料可能写作或转写略有差异，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "暂不考中文含义，只做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "这个词短，适合练 خ、و、ش 的连续识别。"
      },
      {
        id: "assalamu",
        value: "ئەسسالامۇ ئەلەيكۇم",
        latin: "assalamu alaykum",
        meaning: "问候语、愿平安",
        theme: "问候",
        parts: ["ئەسسالامۇ", "ئەلەيكۇم"],
        standardNote: "候选礼貌问候，需确认教学说明和场景。",
        variantNote: "宗教/文化语境需单独说明，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "暂不考中文含义，只做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "先把它看成两个词，不急着一次背完整。"
      }
    ]
  },
  {
    id: "pronouns",
    kind: "vocab",
    title: "我、你、他",
    letters: ["مەن", "سىز", "سەن", "ئۇ", "بىز"],
    goal: "认识最基础人称词形，并把礼貌和亲近说法分开",
    status: "待审校",
    items: [
      {
        id: "men",
        value: "مەن",
        latin: "men",
        meaning: "我",
        theme: "我、你、他",
        parts: ["م", "ە", "ن"],
        standardNote: "候选标准人称词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认，不考语法变化。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "短词，适合练 م 和 ن。"
      },
      {
        id: "siz",
        value: "سىز",
        latin: "siz",
        meaning: "你、您",
        theme: "我、你、他",
        parts: ["س", "ى", "ز"],
        standardNote: "候选礼貌/正式第二人称。",
        variantNote: "和 سەن 的关系要在正式词条里说明。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认，不考礼貌等级。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "和 سەن 同组比较，但不要混成一个答案。"
      },
      {
        id: "sen",
        value: "سەن",
        latin: "sen",
        meaning: "你",
        theme: "我、你、他",
        parts: ["س", "ە", "ن"],
        standardNote: "候选亲近/非正式第二人称。",
        variantNote: "使用场景和礼貌程度需母语者确认。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认，不考礼貌等级。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "和 سىز 的区别先看中间和结尾字母。"
      },
      {
        id: "u-pronoun",
        value: "ئۇ",
        latin: "u",
        meaning: "他、她、它",
        theme: "我、你、他",
        parts: ["ئ", "ۇ"],
        standardNote: "候选第三人称词。",
        variantNote: "中文他/她/它的区分不能直接套入维吾尔语，待审校说明。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认，不考语法变化。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "这是短词，但也和元音 ئۇ 视觉相关。"
      },
      {
        id: "biz",
        value: "بىز",
        latin: "biz",
        meaning: "我们",
        theme: "我、你、他",
        parts: ["ب", "ى", "ز"],
        standardNote: "候选第一人称复数。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认，不考语法变化。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "和 سىز 一起看，注意开头字母不同。"
      }
    ]
  },
  {
    id: "family",
    kind: "vocab",
    title: "家庭、基础称呼",
    letters: ["ئانا", "ئاپا", "ئاتا", "دادا", "ئائىلە", "ئوغۇل", "قىز", "ئاكا", "ئىنىم", "سىڭىل"],
    goal: "把标准主词、家庭称呼和基础亲属词分开记录，不设唯一答案",
    status: "待审校",
    items: [
      {
        id: "ana-family",
        value: "ئانا",
        latin: "ana",
        meaning: "妈妈、母亲",
        theme: "家庭、基础称呼",
        parts: ["ئا", "ن", "ا"],
        standardNote: "候选标准主词，需确认。",
        variantNote: "和 ئاپا 的关系需母语者确认。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考标准/变体判断。",
        reviewStatus: "待母语者审校",
        sourceNote: "来自第二单元预览和用户提醒，进入审校队列。",
        tip: "先记词形，不急着排除 ئاپا。"
      },
      {
        id: "apa-family",
        value: "ئاپا",
        latin: "apa",
        meaning: "妈妈、家庭称呼变体",
        theme: "家庭、基础称呼",
        parts: ["ئا", "پ", "ا"],
        standardNote: "可能为家庭/口语称呼，需确认。",
        variantNote: "用户已提醒它也可表示妈妈。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考标准/变体判断。",
        reviewStatus: "待母语者审校",
        sourceNote: "来自第二单元预览和用户提醒，进入审校队列。",
        tip: "和 ئانا 比较：中间是 پ。"
      },
      {
        id: "ata-family",
        value: "ئاتا",
        latin: "ata",
        meaning: "爸爸、父亲",
        theme: "家庭、基础称呼",
        parts: ["ئا", "ت", "ا"],
        standardNote: "候选标准主词，需确认。",
        variantNote: "和 دادا 的关系需母语者确认。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考标准/变体判断。",
        reviewStatus: "待母语者审校",
        sourceNote: "来自第二单元预览和用户提醒，进入审校队列。",
        tip: "和 ئانا 结构相似，中间字母不同。"
      },
      {
        id: "dada-family",
        value: "دادا",
        latin: "dada",
        meaning: "爸爸、家庭称呼变体",
        theme: "家庭、基础称呼",
        parts: ["د", "ا", "د", "ا"],
        standardNote: "可能为家庭/口语称呼，需确认。",
        variantNote: "用户已提醒它也可表示爸爸。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考标准/变体判断。",
        reviewStatus: "待母语者审校",
        sourceNote: "来自第二单元预览和用户提醒，进入审校队列。",
        tip: "د 后面通常不继续连接，所以词形里会看到断开。"
      },
      {
        id: "aile-family",
        value: "ئائىلە",
        latin: "aile",
        meaning: "家庭、家人",
        theme: "家庭、基础称呼",
        parts: ["ئا", "ئى", "لە"],
        standardNote: "候选基础名词，需母语者确认教学主词。",
        variantNote: "中文“家/家庭/家人”的边界需在例句中继续审校。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考亲属关系细分。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Institute 学习者词表，进入项目审校队列。",
        tip: "两个元音符号连续出现，先分成 ئا、ئى、لە 三块。"
      },
      {
        id: "oghul-family",
        value: "ئوغۇل",
        latin: "oghul",
        meaning: "儿子、男孩",
        theme: "家庭、基础称呼",
        parts: ["ئو", "غ", "ۇل"],
        standardNote: "候选基础亲属/人物词，需母语者确认语境。",
        variantNote: "可表示儿子或男孩，正式课程需用例句区分。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考语义细分。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Institute 学习者词表，进入项目审校队列。",
        tip: "注意 غ 在中间，和 ق、خ 分开看。"
      },
      {
        id: "qiz-family",
        value: "قىز",
        latin: "qiz",
        meaning: "女儿、女孩",
        theme: "家庭、基础称呼",
        parts: ["ق", "ى", "ز"],
        standardNote: "候选基础亲属/人物词，需母语者确认语境。",
        variantNote: "可表示女儿或女孩，正式课程需用例句区分。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考语义细分。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Institute 学习者词表，进入项目审校队列。",
        tip: "短词，适合复习 ق、ى、ز。"
      },
      {
        id: "aka-family",
        value: "ئاكا",
        latin: "aka",
        meaning: "哥哥、兄长",
        theme: "家庭、基础称呼",
        parts: ["ئا", "ك", "ا"],
        standardNote: "候选基础亲属称呼，需母语者确认使用场景。",
        variantNote: "亲属称呼可能随年龄、关系和礼貌场景变化，待审校。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考亲属关系细分。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Institute 学习者词表，进入项目审校队列。",
        tip: "和 ئاپا 比较：中间是 ك。"
      },
      {
        id: "inim-family",
        value: "ئىنىم",
        latin: "inim",
        meaning: "我的弟弟、弟弟称呼",
        theme: "家庭、基础称呼",
        parts: ["ئى", "نى", "م"],
        standardNote: "候选亲属称呼，先作为学习预览。",
        variantNote: "该词带有“我的”语义，是否适合初学阶段需母语者确认。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考所有格和称谓变化。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Institute 学习者词表，进入项目审校队列。",
        tip: "先记它和 ئاكا 是一组，不急着学语法变化。"
      },
      {
        id: "singil-family",
        value: "سىڭىل",
        latin: "singil",
        meaning: "妹妹",
        theme: "家庭、基础称呼",
        parts: ["سى", "ڭى", "ل"],
        standardNote: "候选基础亲属称呼，需母语者确认使用场景。",
        variantNote: "和 ئاپا 的姐姐/妈妈用法关系需要单独审校说明。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考亲属关系细分。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Institute 学习者词表，进入项目审校队列。",
        tip: "这里有 ڭ，适合复习 ك / گ / ڭ 这一组。"
      }
    ]
  },
  {
    id: "numbers",
    kind: "vocab",
    title: "数字 1-10",
    letters: ["بىر", "ئىككى", "ئۈچ", "تۆت", "بەش", "ئالتە", "يەتتە", "سەككىز", "توققۇز", "ئون"],
    goal: "先认识 1 到 10 的词形，后续再做数字专项",
    status: "待审校",
    items: [
      {
        id: "one",
        value: "بىر",
        latin: "bir",
        meaning: "一",
        theme: "数字 1-10",
        parts: ["ب", "ى", "ر"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "短词，注意 ر 后不继续连接。"
      },
      {
        id: "two",
        value: "ئىككى",
        latin: "ikki",
        meaning: "二",
        theme: "数字 1-10",
        parts: ["ئى", "ك", "كى"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "ك 系字母出现两次，适合复习连接。"
      },
      {
        id: "three",
        value: "ئۈچ",
        latin: "üch",
        meaning: "三",
        theme: "数字 1-10",
        parts: ["ئۈ", "چ"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "复习元音 ئۈ 和字母 چ。"
      },
      {
        id: "four",
        value: "تۆت",
        latin: "töt",
        meaning: "四",
        theme: "数字 1-10",
        parts: ["ت", "ۆ", "ت"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "同一个 ت 出现在开头和结尾。"
      },
      {
        id: "five",
        value: "بەش",
        latin: "besh",
        meaning: "五",
        theme: "数字 1-10",
        parts: ["ب", "ە", "ش"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "复习 ب 和 ش。"
      },
      {
        id: "six",
        value: "ئالتە",
        latin: "altë",
        meaning: "六",
        theme: "数字 1-10",
        parts: ["ئا", "ل", "تە"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Institute 学习者词表，进入项目审校队列。",
        tip: "先看 ئا，再看结尾 تە。"
      },
      {
        id: "seven",
        value: "يەتتە",
        latin: "yettë",
        meaning: "七",
        theme: "数字 1-10",
        parts: ["يە", "ت", "تە"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Institute 学习者词表，进入项目审校队列。",
        tip: "ت 连续出现两次，适合练连接后的形状。"
      },
      {
        id: "eight",
        value: "سەككىز",
        latin: "sakkiz",
        meaning: "八",
        theme: "数字 1-10",
        parts: ["سە", "ك", "كىز"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Institute 学习者词表，进入项目审校队列。",
        tip: "ك 出现两次，注意中间连接。"
      },
      {
        id: "nine",
        value: "توققۇز",
        latin: "toqquz",
        meaning: "九",
        theme: "数字 1-10",
        parts: ["تو", "ق", "قۇز"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Institute 学习者词表，进入项目审校队列。",
        tip: "ق 连续出现两次，和 ك 分开看。"
      },
      {
        id: "ten",
        value: "ئون",
        latin: "on",
        meaning: "十",
        theme: "数字 1-10",
        parts: ["ئو", "ن"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Institute 学习者词表，进入项目审校队列。",
        tip: "短词，先把 ئو 和 ن 看清楚。"
      }
    ]
  },
  {
    id: "animals",
    kind: "vocab",
    title: "动物",
    letters: ["ئىت", "مۈشۈك", "بېلىق", "قۇش", "كالا", "قوي", "توخۇ"],
    goal: "先认识身边和市场里常见动物，不做复数和食物含义区分",
    status: "待审校",
    items: [
      {
        id: "it-animal",
        value: "ئىت",
        latin: "it",
        meaning: "狗",
        theme: "动物",
        parts: ["ئى", "ت"],
        standardNote: "候选基础动物词，需母语者确认。",
        variantNote: "宠物/动物叫法和口语称呼待后续审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Swadesh 词表，进入项目审校队列。",
        tip: "短词，适合复习 ئى 和 ت。"
      },
      {
        id: "mushuk-animal",
        value: "مۈشۈك",
        latin: "müshük",
        meaning: "猫",
        theme: "动物",
        parts: ["مۈ", "شۈ", "ك"],
        standardNote: "候选基础动物词，需母语者确认。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 English Uighur Dictionary，进入项目审校队列。",
        tip: "词里有两个 ئۈ 音相关形状，先慢慢分块。"
      },
      {
        id: "beliq-animal",
        value: "بېلىق",
        latin: "bëliq",
        meaning: "鱼",
        theme: "动物",
        parts: ["بې", "لى", "ق"],
        standardNote: "候选基础动物词，需母语者确认。",
        variantNote: "作为食物或动物时的教学说明需后续补例句。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Swadesh 词表，进入项目审校队列。",
        tip: "结尾 ق 不要和 ك 混。"
      },
      {
        id: "qush-animal",
        value: "قۇش",
        latin: "qush",
        meaning: "鸟",
        theme: "动物",
        parts: ["ق", "ۇ", "ش"],
        standardNote: "候选基础动物词，需母语者确认。",
        variantNote: "可先作为统称，具体鸟类以后再加。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Uyghur Swadesh 词表，进入项目审校队列。",
        tip: "这个词把 ق、ۇ、ش 连在一起。"
      },
      {
        id: "kala-animal",
        value: "كالا",
        latin: "kala",
        meaning: "牛",
        theme: "动物",
        parts: ["ك", "ا", "لا"],
        standardNote: "候选基础动物词，需母语者确认。",
        variantNote: "牛、奶牛、肉类语境需后续分开。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 English Uighur Dictionary，进入项目审校队列。",
        tip: "结构简单，适合复习 ك 和 ل。"
      },
      {
        id: "qoy-animal",
        value: "قوي",
        latin: "qoy",
        meaning: "羊",
        theme: "动物",
        parts: ["قو", "ي"],
        standardNote: "候选基础动物词，需母语者确认。",
        variantNote: "羊和羊肉的用法需后续区分。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 English Uighur Dictionary，进入项目审校队列。",
        tip: "短词，先看 قو，再看结尾 ي。"
      },
      {
        id: "toxu-animal",
        value: "توخۇ",
        latin: "toxu",
        meaning: "鸡",
        theme: "动物",
        parts: ["ت", "و", "خۇ"],
        standardNote: "候选基础动物词，需母语者确认。",
        variantNote: "可表示鸡，也可能和鸡肉语境相关，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 English Uighur Dictionary，进入项目审校队列。",
        tip: "这里复习 خ，不要读成 چ。"
      }
    ]
  },
  {
    id: "vegetables",
    kind: "vocab",
    title: "蔬菜",
    letters: ["پەمىدۇر", "پىياز", "ياڭيۇ", "سەۋزە", "سامساق", "تەرخەمەك"],
    goal: "先认识菜市场里常见的蔬菜词，地区说法继续进入审校",
    status: "待审校",
    items: [
      {
        id: "pemidur-vegetable",
        value: "پەمىدۇر",
        latin: "pemidur",
        meaning: "番茄、西红柿",
        theme: "蔬菜",
        parts: ["پە", "مى", "دۇر"],
        standardNote: "候选常见蔬菜词，需母语者确认教学主词。",
        variantNote: "资料也列 شوخلا 为同义/变体，标准主词和地区用法待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Wiktionary / Learn Entry 蔬菜词表，进入项目审校队列。",
        tip: "词形较长，先分成 پە、مى、دۇر。"
      },
      {
        id: "piyaz-vegetable",
        value: "پىياز",
        latin: "piyaz",
        meaning: "洋葱",
        theme: "蔬菜",
        parts: ["پى", "يا", "ز"],
        standardNote: "候选常见蔬菜词，需母语者确认。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Wiktionary / Learn Entry 蔬菜词表，进入项目审校队列。",
        tip: "注意 پ 开头，结尾是 ز。"
      },
      {
        id: "yangyu-vegetable",
        value: "ياڭيۇ",
        latin: "yangyu",
        meaning: "土豆、马铃薯",
        theme: "蔬菜",
        parts: ["يا", "ڭ", "يۇ"],
        standardNote: "候选常见蔬菜词，需母语者确认标准主词。",
        variantNote: "部分资料也列 بەرەڭگە，标准/地区用法待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Wiktionary / Kaikki 蔬菜词表，进入项目审校队列。",
        tip: "这里有 ڭ，适合复习鼻音字母。"
      },
      {
        id: "sewze-vegetable",
        value: "سەۋزە",
        latin: "sewze",
        meaning: "胡萝卜",
        theme: "蔬菜",
        parts: ["سە", "ۋ", "زە"],
        standardNote: "候选常见蔬菜词，需母语者确认。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Learn Entry / Glosbe 词条，进入项目审校队列。",
        tip: "注意中间 ۋ 和结尾 زە。"
      },
      {
        id: "samsaq-vegetable",
        value: "سامساق",
        latin: "samsaq",
        meaning: "大蒜",
        theme: "蔬菜",
        parts: ["سا", "م", "ساق"],
        standardNote: "候选常见蔬菜词，需母语者确认。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Wiktionary 词条，进入项目审校队列。",
        tip: "س 出现两次，结尾 ق 要看清。"
      },
      {
        id: "terxemek-vegetable",
        value: "تەرخەمەك",
        latin: "terxemek",
        meaning: "黄瓜",
        theme: "蔬菜",
        parts: ["تەر", "خە", "مەك"],
        standardNote: "候选常见蔬菜词，需母语者确认。",
        variantNote: "资料也列其他译名，标准/地区用法待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考 Learn Entry / Logos Dictionary 词条，进入项目审校队列。",
        tip: "词形较长，先找到中间的 خ。"
      }
    ]
  }
];

  window.ANA_TILIM_VOCAB = {
    vocabGroups
  };
})();
