(() => {
const vocabGroups = [
  {
    id: "greetings",
    kind: "vocab",
    title: "问候",
    letters: ["ياخشىمۇسىز", "رەھمەت", "خوش", "ئەسسالامۇ ئەلەيكۇم"],
    goal: "先认识最常见的问候和礼貌词形，中文只做预览",
    status: "待审校",
    items: [
      {
        id: "yaxshimusiz",
        value: "ياخشىمۇسىز",
        latin: "yaxshimusiz",
        meaning: "你好、你好吗",
        theme: "问候",
        parts: ["ياخشى", "مۇ", "سىز"],
        standardNote: "候选标准问候词形，需母语者确认使用场景。",
        variantNote: "可能兼有问候和询问状态用法，语境待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "暂不考中文含义，只做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "词形较长，先分成 ياخشى、مۇ、سىز 三块看。"
      },
      {
        id: "rahmat",
        value: "رەھمەت",
        latin: "rehmet",
        meaning: "谢谢",
        theme: "问候",
        parts: ["رە", "ھمەت"],
        standardNote: "候选礼貌词，需确认标准转写和发音。",
        variantNote: "口语发音和转写可能有差异，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "暂不考中文含义，只做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "先看 ر 和 ھ，再整体记住词形。"
      },
      {
        id: "xosh",
        value: "خوش",
        latin: "xosh",
        meaning: "再见、告别",
        theme: "问候",
        parts: ["خ", "و", "ش"],
        standardNote: "候选告别词，需确认使用范围。",
        variantNote: "不同资料可能写作或转写略有差异，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "暂不考中文含义，只做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "这个词短，适合练 خ、و、ش 的连续识别。"
      },
      {
        id: "assalamu",
        value: "ئەسسالامۇ ئەلەيكۇم",
        latin: "assalamu alaykum",
        meaning: "问候语、愿平安",
        theme: "问候",
        parts: ["ئەسسالامۇ", "ئەلەيكۇم"],
        standardNote: "候选礼貌问候，需确认教学说明和场景。",
        variantNote: "宗教/文化语境需单独说明，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "暂不考中文含义，只做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "先把它看成两个词，不急着一次背完整。"
      }
    ]
  },
  {
    id: "pronouns",
    kind: "vocab",
    title: "我、你、他",
    letters: ["مەن", "سىز", "سەن", "ئۇ", "بىز"],
    goal: "认识最基础人称词形，并把礼貌和亲近说法分开",
    status: "待审校",
    items: [
      {
        id: "men",
        value: "مەن",
        latin: "men",
        meaning: "我",
        theme: "我、你、他",
        parts: ["م", "ە", "ن"],
        standardNote: "候选标准人称词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认，不考语法变化。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "短词，适合练 م 和 ن。"
      },
      {
        id: "siz",
        value: "سىز",
        latin: "siz",
        meaning: "你、您",
        theme: "我、你、他",
        parts: ["س", "ى", "ز"],
        standardNote: "候选礼貌/正式第二人称。",
        variantNote: "和 سەن 的关系要在正式词条里说明。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认，不考礼貌等级。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "和 سەن 同组比较，但不要混成一个答案。"
      },
      {
        id: "sen",
        value: "سەن",
        latin: "sen",
        meaning: "你",
        theme: "我、你、他",
        parts: ["س", "ە", "ن"],
        standardNote: "候选亲近/非正式第二人称。",
        variantNote: "使用场景和礼貌程度需母语者确认。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认，不考礼貌等级。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "和 سىز 的区别先看中间和结尾字母。"
      },
      {
        id: "u-pronoun",
        value: "ئۇ",
        latin: "u",
        meaning: "他、她、它",
        theme: "我、你、他",
        parts: ["ئ", "ۇ"],
        standardNote: "候选第三人称词。",
        variantNote: "中文他/她/它的区分不能直接套入维吾尔语，待审校说明。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认，不考语法变化。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "这是短词，但也和元音 ئۇ 视觉相关。"
      },
      {
        id: "biz",
        value: "بىز",
        latin: "biz",
        meaning: "我们",
        theme: "我、你、他",
        parts: ["ب", "ى", "ز"],
        standardNote: "候选第一人称复数。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认，不考语法变化。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "和 سىز 一起看，注意开头字母不同。"
      }
    ]
  },
  {
    id: "family",
    kind: "vocab",
    title: "家庭、基础称呼",
    letters: ["ئانا", "ئاپا", "ئاتا", "دادا"],
    goal: "把标准主词和家庭口语变体分开记录，不设唯一答案",
    status: "待审校",
    items: [
      {
        id: "ana-family",
        value: "ئانا",
        latin: "ana",
        meaning: "妈妈、母亲",
        theme: "家庭、基础称呼",
        parts: ["ئا", "ن", "ا"],
        standardNote: "候选标准主词，需确认。",
        variantNote: "和 ئاپا 的关系需母语者确认。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考标准/变体判断。",
        reviewStatus: "待母语者审校",
        sourceNote: "来自第二单元预览和用户提醒，进入审校队列。",
        tip: "先记词形，不急着排除 ئاپا。"
      },
      {
        id: "apa-family",
        value: "ئاپا",
        latin: "apa",
        meaning: "妈妈、家庭称呼变体",
        theme: "家庭、基础称呼",
        parts: ["ئا", "پ", "ا"],
        standardNote: "可能为家庭/口语称呼，需确认。",
        variantNote: "用户已提醒它也可表示妈妈。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考标准/变体判断。",
        reviewStatus: "待母语者审校",
        sourceNote: "来自第二单元预览和用户提醒，进入审校队列。",
        tip: "和 ئانا 比较：中间是 پ。"
      },
      {
        id: "ata-family",
        value: "ئاتا",
        latin: "ata",
        meaning: "爸爸、父亲",
        theme: "家庭、基础称呼",
        parts: ["ئا", "ت", "ا"],
        standardNote: "候选标准主词，需确认。",
        variantNote: "和 دادا 的关系需母语者确认。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考标准/变体判断。",
        reviewStatus: "待母语者审校",
        sourceNote: "来自第二单元预览和用户提醒，进入审校队列。",
        tip: "和 ئانا 结构相似，中间字母不同。"
      },
      {
        id: "dada-family",
        value: "دادا",
        latin: "dada",
        meaning: "爸爸、家庭称呼变体",
        theme: "家庭、基础称呼",
        parts: ["د", "ا", "د", "ا"],
        standardNote: "可能为家庭/口语称呼，需确认。",
        variantNote: "用户已提醒它也可表示爸爸。",
        acceptableAnswer: "正式考核前不设唯一答案。",
        testPolicy: "只练词形，不考标准/变体判断。",
        reviewStatus: "待母语者审校",
        sourceNote: "来自第二单元预览和用户提醒，进入审校队列。",
        tip: "د 后面通常不继续连接，所以词形里会看到断开。"
      }
    ]
  },
  {
    id: "numbers",
    kind: "vocab",
    title: "数字 1-5",
    letters: ["بىر", "ئىككى", "ئۈچ", "تۆت", "بەش"],
    goal: "先认识 1 到 5 的词形，后续再做数字专项",
    status: "待审校",
    items: [
      {
        id: "one",
        value: "بىر",
        latin: "bir",
        meaning: "一",
        theme: "数字 1-5",
        parts: ["ب", "ى", "ر"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "短词，注意 ر 后不继续连接。"
      },
      {
        id: "two",
        value: "ئىككى",
        latin: "ikki",
        meaning: "二",
        theme: "数字 1-5",
        parts: ["ئى", "ك", "كى"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "ك 系字母出现两次，适合复习连接。"
      },
      {
        id: "three",
        value: "ئۈچ",
        latin: "üch",
        meaning: "三",
        theme: "数字 1-5",
        parts: ["ئۈ", "چ"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "复习元音 ئۈ 和字母 چ。"
      },
      {
        id: "four",
        value: "تۆت",
        latin: "töt",
        meaning: "四",
        theme: "数字 1-5",
        parts: ["ت", "ۆ", "ت"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "同一个 ت 出现在开头和结尾。"
      },
      {
        id: "five",
        value: "بەش",
        latin: "besh",
        meaning: "五",
        theme: "数字 1-5",
        parts: ["ب", "ە", "ش"],
        standardNote: "候选数字词。",
        variantNote: "暂无变体备注，待审校。",
        acceptableAnswer: "现阶段只练词形，不设最终可接受答案。",
        testPolicy: "可做词形辨认和输入。",
        reviewStatus: "待母语者审校",
        sourceNote: "参考公开学习资料，进入项目审校队列。",
        tip: "复习 ب 和 ش。"
      }
    ]
  }
];

  window.ANA_TILIM_VOCAB = {
    vocabGroups
  };
})();
